In [ ]:
import sys
!{sys.executable} -m pip install yfinance
import yfinance as yf
import pandas as pd
import numpy as np

Collecting yfinance
  Downloading yfinance-1.6.0-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.0/148.0 kB 2.9 MB/s eta 0:00:00[31m3.3 MB/s eta 0:00:01
Collecting pytz>=2022.5
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.3/508.3 kB 13.5 MB/s eta 0:00:00
Collecting yfinance
  Downloading yfinance-1.5.2-py2.py3-none-any.whl (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.1/144.1 kB 18.2 MB/s eta 0:00:00
  Downloading yfinance-1.5.1-py2.py3-none-any.whl (144 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.2/144.2 kB 17.4 MB/s eta 0:00:00
  Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 33.1 MB/s eta 0:00:00
  Downloading yfinance-1.4.0-py2.py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.7/137.7 kB 20.6 MB/s eta 0:00:00
  Downloading yfinance-1.3.0-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 19.9 MB/s eta 0:00:00
  Downloading yfinance-1.2.2-py2.py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.8/130.8 kB 19.9 MB/s eta 0:00:00
  Downloading yfinance-1.2.1-py2.py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 16.6 MB/s eta 0:00:00
  Downloading yfinance-1.2.0-py2.py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 21.2 MB/s eta 0:00:00
Collecting requests>=2.31
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 10.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16.5 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (1.21.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (4.11.1)
Collecting curl_cffi<0.14,>=0.7
  Downloading curl_cffi-0.13.0-cp39-abi3-macosx_10_9_x86_64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 47.9 MB/s eta 0:00:00m eta 0:00:010:01:01
Collecting frozendict>=2.3.4
  Downloading frozendict-2.4.7-cp39-cp39-macosx_10_9_x86_64.whl (38 kB)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Requirement already satisfied: pandas>=1.3.0 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (1.4.4)
Collecting protobuf>=3.19.0
  Downloading protobuf-6.33.6-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 427.7/427.7 kB 32.1 MB/s eta 0:00:00
Requirement already satisfied: platformdirs>=2.0.0 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from yfinance) (2.5.2)
Collecting peewee>=3.16.2
  Downloading peewee-4.4.0-py3-none-any.whl (191 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.2/191.2 kB 36.1 MB/s eta 0:00:00
Collecting websockets>=13.0
  Downloading websockets-15.0.1-cp39-cp39-macosx_10_9_x86_64.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.1/173.1 kB 23.4 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>1.2 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.1)
Requirement already satisfied: cffi>=1.12.0 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.15.1)
Collecting certifi>=2024.2.2
  Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.0/137.0 kB 20.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: pycparser in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in /Users/jessicakiroff/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas>=1.3.0->yfinance) (1.16.0)
Installing collected packages: pytz, multitasking, websockets, protobuf, peewee, frozendict, certifi, requests, curl_cffi, yfinance
  Attempting uninstall: pytz
    Found existing installation: pytz 2022.1
    Uninstalling pytz-2022.1:
      Successfully uninstalled pytz-2022.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2022.9.24
    Uninstalling certifi-2022.9.24:
      Successfully uninstalled certifi-2022.9.24
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.20 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.20 requires nbformat==5.4.0, but you have nbformat 5.5.0 which is incompatible.
conda-repo-cli 1.0.20 requires requests==2.28.1, but you have requests 2.32.5 which is incompatible.
Successfully installed certifi-2026.7.22 curl_cffi-0.13.0 frozendict-2.4.7 multitasking-0.0.13 peewee-4.4.0 protobuf-6.33.6 pytz-2026.3.post1 requests-2.32.5 websockets-15.0.1 yfinance-1.2.0

In [3]:
yf.download?

Signature:
yf.download(
    tickers,
    start=None,
    end=None,
    actions=False,
    threads=True,
    ignore_tz=None,
    group_by='column',
    auto_adjust=True,
    back_adjust=False,
    repair=False,
    keepna=False,
    progress=True,
    period=None,
    interval='1d',
    prepost=False,
    rounding=False,
    timeout=10,
    session=None,
    multi_level_index=True,
) -> Optional[pandas.core.frame.DataFrame]
Docstring:
Download yahoo tickers
:Parameters:
    tickers : str, list
        List of tickers to download
    period : str
        Valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        Default: 1mo
        Either Use period parameter or use start and end
    interval : str
        Valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        Intraday data cannot extend last 60 days
    start: str
        Download start date string (YYYY-MM-DD) or _datetime, inclusive.
        Default is 99 years ago
        E.g. for start="2020-01-01", the first data point will be on "2020-01-01"
    end: str
        Download end date string (YYYY-MM-DD) or _datetime, exclusive.
        Default is now
        E.g. for end="2023-01-01", the last data point will be on "2022-12-31"
    group_by : str
        Group by 'ticker' or 'column' (default)
    prepost : bool
        Include Pre and Post market data in results?
        Default is False
    auto_adjust: bool
        Adjust all OHLC automatically? Default is True
    repair: bool
        Detect currency unit 100x mixups and attempt repair
        Default is False
    keepna: bool
        Keep NaN rows returned by Yahoo?
        Default is False
    actions: bool
        Download dividend + stock splits data. Default is False
    threads: bool / int
        How many threads to use for mass downloading. Default is True
    ignore_tz: bool
        When combining from different timezones, ignore that part of datetime.
        Default depends on interval. Intraday = False. Day+ = True.
    rounding: bool
        Optional. Round values to 2 decimal places?
    timeout: None or float
        If not None stops waiting for a response after given number of
        seconds. (Can also be a fraction of a second e.g. 0.01)
    session: None or Session
        Optional. Pass your own session object to be used for all requests
    multi_level_index: bool
        Optional. Always return a MultiIndex DataFrame? Default is True
File:      ~/opt/anaconda3/lib/python3.9/site-packages/yfinance/multi.py
Type:      function

In [5]:
tickers = ["NVDA", "JNJ", "XOM", "JPM", "WMT", "BTC-USD", "GLD"]
data = yf.download(tickers, start="2022-08-25", end="2025-08-25", threads=False)
data.head()

[*********************100%***********************]  7 of 7 completed

Price              Close                                                 \
Ticker           BTC-USD         GLD         JNJ         JPM       NVDA
Date
2022-08-25  21600.904297  163.750000  149.917923  107.598663  17.863409
2022-08-26  20260.019531  161.759995  147.352448  104.077072  16.214987
2022-08-27  20041.738281         NaN         NaN         NaN        NaN
2022-08-28  19616.814453         NaN         NaN         NaN        NaN
2022-08-29  20297.994141  161.860001  146.213226  103.822937  15.757253

Price                                     High                          ...  \
Ticker            WMT        XOM       BTC-USD         GLD         JNJ  ...
Date                                                                    ...
2022-08-25  43.224026  86.920158  21789.636719  163.990005  150.016595  ...
2022-08-26  41.865620  85.849991  21804.908203  163.610001  150.249798  ...
2022-08-27        NaN        NaN  20340.775391         NaN         NaN  ...
2022-08-28        NaN        NaN  20139.054688         NaN         NaN  ...
2022-08-29  42.272827  87.823647  20357.462891  162.619995  146.966715  ...

Price            Open                             Volume             \
Ticker           NVDA        WMT        XOM      BTC-USD        GLD
Date
2022-08-25  16.797368  43.036330  86.771039  31028679593  2857500.0
2022-08-26  17.807566  43.300373  86.639451  42326789564  6689300.0
2022-08-27        NaN        NaN        NaN  30116729776        NaN
2022-08-28        NaN        NaN        NaN  24366810591        NaN
2022-08-29  15.975647  41.620668  86.121908  32637854078  4702300.0

Price
Ticker            JNJ         JPM         NVDA         WMT         XOM
Date
2022-08-25  5678700.0  10758900.0  770691000.0  19414500.0  15305700.0
2022-08-26  5667100.0  11276200.0  769127000.0  21331800.0  15531400.0
2022-08-27        NaN         NaN          NaN         NaN         NaN
2022-08-28        NaN         NaN          NaN         NaN         NaN
2022-08-29  5259200.0   8117300.0  496132000.0  17381700.0  23059200.0

[5 rows x 35 columns]

In [6]:
data.shape

(1096, 35)

In [7]:
data.columns

MultiIndex([( 'Close', 'BTC-USD'),
            ( 'Close',     'GLD'),
            ( 'Close',     'JNJ'),
            ( 'Close',     'JPM'),
            ( 'Close',    'NVDA'),
            ( 'Close',     'WMT'),
            ( 'Close',     'XOM'),
            (  'High', 'BTC-USD'),
            (  'High',     'GLD'),
            (  'High',     'JNJ'),
            (  'High',     'JPM'),
            (  'High',    'NVDA'),
            (  'High',     'WMT'),
            (  'High',     'XOM'),
            (   'Low', 'BTC-USD'),
            (   'Low',     'GLD'),
            (   'Low',     'JNJ'),
            (   'Low',     'JPM'),
            (   'Low',    'NVDA'),
            (   'Low',     'WMT'),
            (   'Low',     'XOM'),
            (  'Open', 'BTC-USD'),
            (  'Open',     'GLD'),
            (  'Open',     'JNJ'),
            (  'Open',     'JPM'),
            (  'Open',    'NVDA'),
            (  'Open',     'WMT'),
            (  'Open',     'XOM'),
            ('Volume', 'BTC-USD'),
            ('Volume',     'GLD'),
            ('Volume',     'JNJ'),
            ('Volume',     'JPM'),
            ('Volume',    'NVDA'),
            ('Volume',     'WMT'),
            ('Volume',     'XOM')],
           names=['Price', 'Ticker'])

In [8]:
data.isna().sum()

Price   Ticker
Close   BTC-USD      0
        GLD        345
        JNJ        345
        JPM        345
        NVDA       345
        WMT        345
        XOM        345
High    BTC-USD      0
        GLD        345
        JNJ        345
        JPM        345
        NVDA       345
        WMT        345
        XOM        345
Low     BTC-USD      0
        GLD        345
        JNJ        345
        JPM        345
        NVDA       345
        WMT        345
        XOM        345
Open    BTC-USD      0
        GLD        345
        JNJ        345
        JPM        345
        NVDA       345
        WMT        345
        XOM        345
Volume  BTC-USD      0
        GLD        345
        JNJ        345
        JPM        345
        NVDA       345
        WMT        345
        XOM        345
dtype: int64

In [9]:
data_clean = data.dropna()

In [10]:
data_clean.shape

(751, 35)

In [11]:
data_clean.isna().sum()

Price   Ticker
Close   BTC-USD    0
        GLD        0
        JNJ        0
        JPM        0
        NVDA       0
        WMT        0
        XOM        0
High    BTC-USD    0
        GLD        0
        JNJ        0
        JPM        0
        NVDA       0
        WMT        0
        XOM        0
Low     BTC-USD    0
        GLD        0
        JNJ        0
        JPM        0
        NVDA       0
        WMT        0
        XOM        0
Open    BTC-USD    0
        GLD        0
        JNJ        0
        JPM        0
        NVDA       0
        WMT        0
        XOM        0
Volume  BTC-USD    0
        GLD        0
        JNJ        0
        JPM        0
        NVDA       0
        WMT        0
        XOM        0
dtype: int64

In [16]:
close = data_clean["Close"]
close.head()

Ticker,BTC-USD,GLD,JNJ,JPM,NVDA,WMT,XOM
Date,,,,,,,
2022-08-25,21600.904297,163.750000,149.917923,107.598663,17.863409,43.224026,86.920158
2022-08-26,20260.019531,161.759995,147.352448,104.077072,16.214987,41.865620,85.849991
2022-08-29,20297.994141,161.860001,146.213226,103.822937,15.757253,42.272827,87.823647
2022-08-30,19796.808594,160.509995,145.701981,103.841095,15.425175,42.145576,84.481560
2022-08-31,20049.763672,159.270004,144.724182,103.223923,15.052209,42.167847,83.850006